services:
  - type: web
    name: backend-auditoria
    env: python
    buildCommand: ""
    startCommand: ./start.sh
    envVars:
      - key: DATABASE_URL
        value: mysql+pymysql://root:IOESIRsCgnadkaSoIPkRasoJsnXJIGgt@yamanote.proxy.rlwy.net:45639/railway